### ISSUE TITLE
Add console command for spinning up worker in release phase

### ISSUE THREAD

**Issue by gijsstegehuis** [robuust/craft-heroku-internal#1]

**Comment by boboldehampsink** [comment]
@gijsstegehuis dit gebeurd automatisch al als er iets in de queue wordt gezet

**Comment by gijsstegehuis** [comment]
Klopt, maar dus niet als er niet iets nieuws in wordt gezet.
Zoals nu bij Leenders wordt er 10x per dag gereleased en stalled de queue vaak.

**Comment by boboldehampsink** [comment]
Oh zo. Eigenlijk zou hij na release altijd moeten checken of er iets in de queue zit, en dan worker opstarten dus. Check.

**Comment by boboldehampsink** [comment]
4a8c889ad7128edd84690925e43292fefb0916f5 zou dit moeten fixen, nu in test
